In [1]:
import pandas as pd
import numpy as np
%matplotlib inline

In [2]:
df = pd.read_excel("Wine.xls")
df.head()

,Type,Alcohol,Malic_Acid,Ash,Ash_Alcalinity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280_OD315,Proline
0,A,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,A,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,A,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,A,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,A,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [3]:
input_vars = df.columns[1:]
input_vars

Index(['Alcohol', 'Malic_Acid', 'Ash', 'Ash_Alcalinity', 'Magnesium',
       'Total_Phenols', 'Flavanoids', 'Nonflavanoid_Phenols',
       'Proanthocyanins', 'Color_Intensity', 'Hue', 'OD280_OD315', 'Proline'],
      dtype='object')

## Without normalization

In [4]:
from sklearn.decomposition import PCA

pca = PCA(0.95)
principalComponents = pca.fit_transform(df[input_vars])

In [5]:
pca.explained_variance_ratio_

array([0.99809123])

In [6]:
principal_df = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1'])
principal_df.head(15)

    principal component 1
0              318.562979
1              303.097420
2              438.061133
3              733.240139
4              -11.571428
5              703.231192
6              542.971581
7              548.401860
8              298.036863
9              298.049553
10             763.079712
11             532.943228
12             572.834410
13             402.925358
14             800.053394

## With normalization

In [7]:
from sklearn.preprocessing import StandardScaler

# Separating out the features
x = df[df.columns[1:]]

# Standardizing the features
x = StandardScaler().fit_transform(x)
x

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  0.36217728,
         1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 0.33275817,  1.74474449, -0.38935541, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 0.20923168,  0.22769377,  0.01273209, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.39508604,  1.58316512,  1.36520822, ..., -1.52437837,
        -1.42894777, -0.59516041]])

In [8]:
pca = PCA(0.95)
principalComponents = pca.fit_transform(x)

In [9]:
pca.explained_variance_ratio_

array([0.36198848, 0.1920749 , 0.11123631, 0.0706903 , 0.06563294,
       0.04935823, 0.04238679, 0.02680749, 0.02222153, 0.01930019])

In [10]:
principal_df = pd.DataFrame(data = principalComponents
             , columns = ['pc_1', 'pc_2', 'pc_3', 'pc_4', 'pc_5', 'pc_6', 'pc_7', 'pc_8', 'pc_9', 'pc_10'])
principal_df.head(15)

,pc_1,pc_2,pc_3,pc_4,pc_5,pc_6,pc_7,pc_8,pc_9,pc_10
0,3.316751,-1.443463,-0.165739,-0.215631,0.693043,-0.223880,0.596427,0.065139,0.641443,1.020956
1,2.209465,0.333393,-2.026457,-0.291358,-0.257655,-0.927120,0.053776,1.024416,-0.308847,0.159701
2,2.516740,-1.031151,0.982819,0.724902,-0.251033,0.549276,0.424205,-0.344216,-1.177834,0.113361
3,3.757066,-2.756372,-0.176192,0.567983,-0.311842,0.114431,-0.383337,0.643593,0.052544,0.239413
4,1.008908,-0.869831,2.026688,-0.409766,0.298458,-0.406520,0.444074,0.416700,0.326819,-0.078366
5,3.050254,-2.122401,-0.629396,-0.515637,-0.632019,0.123431,0.401654,0.394893,-0.152146,-0.101996
6,2.449090,-1.174850,-0.977095,-0.065831,-1.027762,-0.620121,0.052891,-0.371934,-0.457016,1.016563
7,2.059437,-1.608963,0.146282,-1.192608,0.076903,-1.439806,0.032376,0.232979,0.123370,0.735600
8,2.510874,-0.918071,-1.770969,0.056270,-0.892257,-0.129181,0.125285,-0.499578,0.606589,0.174107
9,2.753628,-0.789438,-0.984247,0.349382,-0.468553,0.163392,-0.874352,0.150580,0.230489,0.179420
10,3.479737,-1.302333,-0.422735,0.026842,-0.338375,-0.182902,0.248162,-1.206611,-0.524574,-0.214538
11,1.754753,-0.611977,-1.190878,-0.890164,-0.738573,-0.553055,-0.434266,-0.985127,-0.474030,0.220283
12,2.113462,-0.675706,-0.865086,-0.356438,-1.209929,-0.215076,-0.242597,-0.461506,-0.878813,-0.096505
13,3.458157,-1.130630,-1.204276,0.162458,-2.023127,0.745781,1.475773,-0.380386,-0.025702,-0.244653
14,4.312784,-2.095976,-1.263913,0.305773,-1.029693,0.795643,0.999971,-0.404891,-0.840343,-0.364433